name: "Testing"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - run: npm ci
    - name: npm mock tests
      run: npm run test -- --testPathIgnorePatterns hc-releases.live.test.js

    # only use the live auth token for the tests that require it
    - name: npm live tests
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_DOWNLOAD_RELAPI }}
      run: |
        npm test hc-releases.live.test.js
